[package]
name = "core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
annotation-rs = "0.1.0"
time = { version = "0.2", optional = true }
serde = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }
iroha = "0.1.7"
quote = "1.0"
syn = "1.0"
proc-macro2 = "1.0"
thiserror = "1.0"

[features]
default = ["mysql", "json", "data-time"]
mysql = []
postgre-sql = []
sqlite = []
json = ["serde_json", "serde"]
data-time = ["time"]